### ISSUE TITLE
get error when use with nuxt 3.0.0

### ISSUE THREAD

**Issue by azulkipli** [nuxt-community/robots-module#83]
my `package.json`
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "nuxt": "3.0.0",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4"
  },
  "dependencies": {
    "@nuxtjs/robots": "^2.5.0"
  }
}
```
my nuxt config
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    telemetry: false,
    ssr: false,
    css: ['~/assets/css/tailwind.css'],
    postcss: {
        plugins: {
            tailwindcss: {},
            autoprefixer: {},
        },
    },
    modules: ['@nuxtjs/robots'],
})
```

when `pnpm run dev`
got this error

```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

  at getOptions (node_modules/.pnpm/@nuxtjs+robots@2.5.0/node_modules/@nuxtjs/robots/dist/module.js:110:23)
  at nuxtModule (node_modules/.pnpm/@nuxtjs+robots@2.5.0/node_modules/@nuxtjs/robots/dist/module.js:125:36)
  at installModule (node_modules/.pnpm/@nuxt+kit@3.0.0/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/.pnpm/nuxt@3.0.0/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by danielroe** [comment]
You need to be using the newer prerelease version of `@nuxtjs/robots` for Nuxt 3 support - currently v3.0.0-2.
